# Generated by Django 4.1.13 on 2024-01-16 19:16

from django.db import migrations
import django.db.models.deletion
import django_multidb.models.fields.rel


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="current_role",
            field=django_multidb.models.fields.rel.RelField(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="authz.role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=django_multidb.models.fields.rel.RelManyField(
                db_constraint=False, null=True, to="authz.role"
            ),
        ),
    ]
