# Generated by Django 4.1.13 on 2024-01-16 20:19

from django.db import migrations
import django_multidb.models.fields.rel


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0002_alter_user_current_role_alter_user_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=django_multidb.models.fields.rel.RelManyField(
                db_constraint=False, to="authz.permission"
            ),
        ),
    ]
