# Generated by Django 4.1.13 on 2024-01-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0003_alter_role_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(db_constraint=False, to="authz.permission"),
        ),
    ]
