# Generated by Django 4.1.13 on 2024-01-17 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0005_alter_permission_options_alter_role_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="parent",
        ),
    ]
