# Generated by Django 4.1.13 on 2024-01-17 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0006_remove_role_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterModelManagers(
            name="permission",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="role",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
