# Generated by Django 4.1.13 on 2024-01-17 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authz", "0007_alter_permission_options_alter_role_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="authz.role",
            ),
        ),
    ]
